version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/complaints

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  mongo_data:
